/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as auth from "../auth.js";
import type * as crons from "../crons.js";
import type * as e2e from "../e2e.js";
import type * as emails from "../emails.js";
import type * as http from "../http.js";
import type * as lib_admin_addressAudit from "../lib/admin/addressAudit.js";
import type * as lib_admin_contractTemplate from "../lib/admin/contractTemplate.js";
import type * as lib_admin_contracts from "../lib/admin/contracts.js";
import type * as lib_admin_generateContract from "../lib/admin/generateContract.js";
import type * as lib_admin_index from "../lib/admin/index.js";
import type * as lib_admin_lifecycle from "../lib/admin/lifecycle.js";
import type * as lib_admin_managerInvites from "../lib/admin/managerInvites.js";
import type * as lib_admin_monitoring from "../lib/admin/monitoring.js";
import type * as lib_admin_tenantLifecycle from "../lib/admin/tenantLifecycle.js";
import type * as lib_admin_tenantSettings from "../lib/admin/tenantSettings.js";
import type * as lib_admin_tenantSettingsValidation from "../lib/admin/tenantSettingsValidation.js";
import type * as lib_admin_tenants from "../lib/admin/tenants.js";
import type * as lib_app_app from "../lib/app/app.js";
import type * as lib_app_index from "../lib/app/index.js";
import type * as lib_auth_ResendOTP from "../lib/auth/ResendOTP.js";
import type * as lib_auth_ResendOTPPasswordReset from "../lib/auth/ResendOTPPasswordReset.js";
import type * as lib_auth_getCurrentActor from "../lib/auth/getCurrentActor.js";
import type * as lib_auth_getSession from "../lib/auth/getSession.js";
import type * as lib_auth_index from "../lib/auth/index.js";
import type * as lib_auth_sessions from "../lib/auth/sessions.js";
import type * as lib_cart_cart from "../lib/cart/cart.js";
import type * as lib_cart_index from "../lib/cart/index.js";
import type * as lib_crypto_credentials from "../lib/crypto/credentials.js";
import type * as lib_crypto_envelope from "../lib/crypto/envelope.js";
import type * as lib_crypto_index from "../lib/crypto/index.js";
import type * as lib_customer_address from "../lib/customer/address.js";
import type * as lib_customer_cgv from "../lib/customer/cgv.js";
import type * as lib_customer_checkoutContact from "../lib/customer/checkoutContact.js";
import type * as lib_customer_consent from "../lib/customer/consent.js";
import type * as lib_customer_identity from "../lib/customer/identity.js";
import type * as lib_customer_index from "../lib/customer/index.js";
import type * as lib_customer_kpi from "../lib/customer/kpi.js";
import type * as lib_customer_pushEnrollment from "../lib/customer/pushEnrollment.js";
import type * as lib_customer_reachability from "../lib/customer/reachability.js";
import type * as lib_customer_rgpd from "../lib/customer/rgpd.js";
import type * as lib_customer_segments from "../lib/customer/segments.js";
import type * as lib_customer_webPush from "../lib/customer/webPush.js";
import type * as lib_delivery_course from "../lib/delivery/course.js";
import type * as lib_delivery_incidents from "../lib/delivery/incidents.js";
import type * as lib_delivery_index from "../lib/delivery/index.js";
import type * as lib_delivery_quote from "../lib/delivery/quote.js";
import type * as lib_delivery_webhooks from "../lib/delivery/webhooks.js";
import type * as lib_devices_devices from "../lib/devices/devices.js";
import type * as lib_devices_index from "../lib/devices/index.js";
import type * as lib_menuRevalidate_index from "../lib/menuRevalidate/index.js";
import type * as lib_menuRevalidate_revalidateMenuTag from "../lib/menuRevalidate/revalidateMenuTag.js";
import type * as lib_menu_availability from "../lib/menu/availability.js";
import type * as lib_menu_catalog from "../lib/menu/catalog.js";
import type * as lib_menu_categories from "../lib/menu/categories.js";
import type * as lib_menu_index from "../lib/menu/index.js";
import type * as lib_menu_items from "../lib/menu/items.js";
import type * as lib_menu_modifiers from "../lib/menu/modifiers.js";
import type * as lib_menu_photos from "../lib/menu/photos.js";
import type * as lib_menu_publication from "../lib/menu/publication.js";
import type * as lib_menu_serviceHours from "../lib/menu/serviceHours.js";
import type * as lib_notifications_antiAnomaly from "../lib/notifications/antiAnomaly.js";
import type * as lib_notifications_campaigns from "../lib/notifications/campaigns.js";
import type * as lib_notifications_categories from "../lib/notifications/categories.js";
import type * as lib_notifications_dispatch from "../lib/notifications/dispatch.js";
import type * as lib_notifications_dnt from "../lib/notifications/dnt.js";
import type * as lib_notifications_engine from "../lib/notifications/engine.js";
import type * as lib_notifications_index from "../lib/notifications/index.js";
import type * as lib_notifications_marketingCascade from "../lib/notifications/marketingCascade.js";
import type * as lib_notifications_marketingRateLimit from "../lib/notifications/marketingRateLimit.js";
import type * as lib_notifications_notify from "../lib/notifications/notify.js";
import type * as lib_notifications_reachabilityFeedback from "../lib/notifications/reachabilityFeedback.js";
import type * as lib_notifications_refundIssuedTemplate from "../lib/notifications/refundIssuedTemplate.js";
import type * as lib_notifications_templateBounds from "../lib/notifications/templateBounds.js";
import type * as lib_notifications_unsubscribe from "../lib/notifications/unsubscribe.js";
import type * as lib_onboarding_crm from "../lib/onboarding/crm.js";
import type * as lib_onboarding_csv from "../lib/onboarding/csv.js";
import type * as lib_onboarding_gates from "../lib/onboarding/gates.js";
import type * as lib_onboarding_index from "../lib/onboarding/index.js";
import type * as lib_onboarding_milestones from "../lib/onboarding/milestones.js";
import type * as lib_onboarding_pipeline from "../lib/onboarding/pipeline.js";
import type * as lib_onboarding_provisioning from "../lib/onboarding/provisioning.js";
import type * as lib_onboarding_seedData from "../lib/onboarding/seedData.js";
import type * as lib_orders_index from "../lib/orders/index.js";
import type * as lib_orders_orders from "../lib/orders/orders.js";
import type * as lib_orders_status from "../lib/orders/status.js";
import type * as lib_orders_tracking from "../lib/orders/tracking.js";
import type * as lib_orders_workflow from "../lib/orders/workflow.js";
import type * as lib_pricing_contradictions from "../lib/pricing/contradictions.js";
import type * as lib_pricing_defaultRule from "../lib/pricing/defaultRule.js";
import type * as lib_pricing_evaluate from "../lib/pricing/evaluate.js";
import type * as lib_pricing_index from "../lib/pricing/index.js";
import type * as lib_pricing_rules from "../lib/pricing/rules.js";
import type * as lib_printing_index from "../lib/printing/index.js";
import type * as lib_printing_printing from "../lib/printing/printing.js";
import type * as lib_stats_dailyKpis from "../lib/stats/dailyKpis.js";
import type * as lib_stats_index from "../lib/stats/index.js";
import type * as lib_stats_quickStats from "../lib/stats/quickStats.js";
import type * as lib_stats_rangeAggregates from "../lib/stats/rangeAggregates.js";
import type * as lib_stats_revenuePerDay from "../lib/stats/revenuePerDay.js";
import type * as lib_stripe_account from "../lib/stripe/account.js";
import type * as lib_stripe_dispute from "../lib/stripe/dispute.js";
import type * as lib_stripe_fees from "../lib/stripe/fees.js";
import type * as lib_stripe_index from "../lib/stripe/index.js";
import type * as lib_stripe_payment from "../lib/stripe/payment.js";
import type * as lib_stripe_paymentIntent from "../lib/stripe/paymentIntent.js";
import type * as lib_stripe_refund from "../lib/stripe/refund.js";
import type * as lib_stripe_savedCard from "../lib/stripe/savedCard.js";
import type * as lib_stripe_signature from "../lib/stripe/signature.js";
import type * as lib_stripe_status from "../lib/stripe/status.js";
import type * as lib_stripe_webhook from "../lib/stripe/webhook.js";
import type * as lib_stripe_webhookHandler from "../lib/stripe/webhookHandler.js";
import type * as lib_tenancy__probes from "../lib/tenancy/_probes.js";
import type * as lib_tenancy_adminInvitesStore from "../lib/tenancy/adminInvitesStore.js";
import type * as lib_tenancy_appConfigStore from "../lib/tenancy/appConfigStore.js";
import type * as lib_tenancy_audit from "../lib/tenancy/audit.js";
import type * as lib_tenancy_campaignsStore from "../lib/tenancy/campaignsStore.js";
import type * as lib_tenancy_cgvArchive from "../lib/tenancy/cgvArchive.js";
import type * as lib_tenancy_contractsStore from "../lib/tenancy/contractsStore.js";
import type * as lib_tenancy_customer from "../lib/tenancy/customer.js";
import type * as lib_tenancy_customerFiche from "../lib/tenancy/customerFiche.js";
import type * as lib_tenancy_customerOrdersStore from "../lib/tenancy/customerOrdersStore.js";
import type * as lib_tenancy_deliveriesStore from "../lib/tenancy/deliveriesStore.js";
import type * as lib_tenancy_devicesStore from "../lib/tenancy/devicesStore.js";
import type * as lib_tenancy_fuzz from "../lib/tenancy/fuzz.js";
import type * as lib_tenancy_index from "../lib/tenancy/index.js";
import type * as lib_tenancy_menuStore from "../lib/tenancy/menuStore.js";
import type * as lib_tenancy_notificationsStore from "../lib/tenancy/notificationsStore.js";
import type * as lib_tenancy_ordersStore from "../lib/tenancy/ordersStore.js";
import type * as lib_tenancy_paymentsStore from "../lib/tenancy/paymentsStore.js";
import type * as lib_tenancy_pricingRulesStore from "../lib/tenancy/pricingRulesStore.js";
import type * as lib_tenancy_prospectsStore from "../lib/tenancy/prospectsStore.js";
import type * as lib_tenancy_serviceHoursStore from "../lib/tenancy/serviceHoursStore.js";
import type * as lib_tenancy_stripeAccountStore from "../lib/tenancy/stripeAccountStore.js";
import type * as lib_tenancy_tenantActionGuard from "../lib/tenancy/tenantActionGuard.js";
import type * as lib_tenancy_tenantsStore from "../lib/tenancy/tenantsStore.js";
import type * as lib_tenancy_userTenantsStore from "../lib/tenancy/userTenantsStore.js";
import type * as lib_tenancy_usersStore from "../lib/tenancy/usersStore.js";
import type * as lib_tenancy_walletDeviceRegistrationsStore from "../lib/tenancy/walletDeviceRegistrationsStore.js";
import type * as lib_tenancy_walletIncentiveDeliveriesStore from "../lib/tenancy/walletIncentiveDeliveriesStore.js";
import type * as lib_tenancy_walletPassesStore from "../lib/tenancy/walletPassesStore.js";
import type * as lib_tenancy_webPushSubscriptionsStore from "../lib/tenancy/webPushSubscriptionsStore.js";
import type * as lib_tenancy_withTenant from "../lib/tenancy/withTenant.js";
import type * as lib_tenants_branding from "../lib/tenants/branding.js";
import type * as lib_tenants_index from "../lib/tenants/index.js";
import type * as lib_tenants_payment from "../lib/tenants/payment.js";
import type * as lib_tenants_resolution from "../lib/tenants/resolution.js";
import type * as lib_uberDirect_account from "../lib/uberDirect/account.js";
import type * as lib_uberDirect_createDelivery from "../lib/uberDirect/createDelivery.js";
import type * as lib_uberDirect_credentials from "../lib/uberDirect/credentials.js";
import type * as lib_uberDirect_deliveries from "../lib/uberDirect/deliveries.js";
import type * as lib_uberDirect_index from "../lib/uberDirect/index.js";
import type * as lib_uberDirect_quote from "../lib/uberDirect/quote.js";
import type * as lib_uberDirect_webhookEvents from "../lib/uberDirect/webhookEvents.js";
import type * as lib_wallet__constants from "../lib/wallet/_constants.js";
import type * as lib_wallet_bridgeSerialToSession from "../lib/wallet/bridgeSerialToSession.js";
import type * as lib_wallet_checkInstallStatus from "../lib/wallet/checkInstallStatus.js";
import type * as lib_wallet_generatePass from "../lib/wallet/generatePass.js";
import type * as lib_wallet_incentive from "../lib/wallet/incentive.js";
import type * as lib_wallet_index from "../lib/wallet/index.js";
import type * as lib_wallet_internalAuth from "../lib/wallet/internalAuth.js";
import type * as lib_wallet_linkSerial from "../lib/wallet/linkSerial.js";
import type * as lib_wallet_passBuilders from "../lib/wallet/passBuilders.js";
import type * as lib_wallet_passDb from "../lib/wallet/passDb.js";
import type * as lib_wallet_pushPayload from "../lib/wallet/pushPayload.js";
import type * as lib_wallet_registrations from "../lib/wallet/registrations.js";
import type * as lib_wallet_triggerUpdate from "../lib/wallet/triggerUpdate.js";
import type * as lib_wallet_webService from "../lib/wallet/webService.js";
import type * as lib_webhooks_idempotent from "../lib/webhooks/idempotent.js";
import type * as lib_webhooks_index from "../lib/webhooks/index.js";
import type * as migrations from "../migrations.js";
import type * as storage from "../storage.js";
import type * as table_admin from "../table/admin.js";
import type * as table_adminInvites from "../table/adminInvites.js";
import type * as table_appConfig from "../table/appConfig.js";
import type * as table_auditLog from "../table/auditLog.js";
import type * as table_cgvVersions from "../table/cgvVersions.js";
import type * as table_contracts from "../table/contracts.js";
import type * as table_customerOrdersPerTenant from "../table/customerOrdersPerTenant.js";
import type * as table_customers from "../table/customers.js";
import type * as table_deliveries from "../table/deliveries.js";
import type * as table_devices from "../table/devices.js";
import type * as table_feedback from "../table/feedback.js";
import type * as table_menuCategories from "../table/menuCategories.js";
import type * as table_menuItemModifierGroups from "../table/menuItemModifierGroups.js";
import type * as table_menuItems from "../table/menuItems.js";
import type * as table_modifierGroups from "../table/modifierGroups.js";
import type * as table_notifications from "../table/notifications.js";
import type * as table_orders from "../table/orders.js";
import type * as table_payments from "../table/payments.js";
import type * as table_pricingRules from "../table/pricingRules.js";
import type * as table_processedWebhookEvents from "../table/processedWebhookEvents.js";
import type * as table_prospects from "../table/prospects.js";
import type * as table_publishedMenus from "../table/publishedMenus.js";
import type * as table_serviceHours from "../table/serviceHours.js";
import type * as table_tenantCredentials from "../table/tenantCredentials.js";
import type * as table_tenants from "../table/tenants.js";
import type * as table_userTenants from "../table/userTenants.js";
import type * as table_users from "../table/users.js";
import type * as table_walletDeviceRegistrations from "../table/walletDeviceRegistrations.js";
import type * as table_walletIncentiveDeliveries from "../table/walletIncentiveDeliveries.js";
import type * as table_walletPasses from "../table/walletPasses.js";
import type * as table_webPushSubscriptions from "../table/webPushSubscriptions.js";
import type * as utils_generateFunctions from "../utils/generateFunctions.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  auth: typeof auth;
  crons: typeof crons;
  e2e: typeof e2e;
  emails: typeof emails;
  http: typeof http;
  "lib/admin/addressAudit": typeof lib_admin_addressAudit;
  "lib/admin/contractTemplate": typeof lib_admin_contractTemplate;
  "lib/admin/contracts": typeof lib_admin_contracts;
  "lib/admin/generateContract": typeof lib_admin_generateContract;
  "lib/admin/index": typeof lib_admin_index;
  "lib/admin/lifecycle": typeof lib_admin_lifecycle;
  "lib/admin/managerInvites": typeof lib_admin_managerInvites;
  "lib/admin/monitoring": typeof lib_admin_monitoring;
  "lib/admin/tenantLifecycle": typeof lib_admin_tenantLifecycle;
  "lib/admin/tenantSettings": typeof lib_admin_tenantSettings;
  "lib/admin/tenantSettingsValidation": typeof lib_admin_tenantSettingsValidation;
  "lib/admin/tenants": typeof lib_admin_tenants;
  "lib/app/app": typeof lib_app_app;
  "lib/app/index": typeof lib_app_index;
  "lib/auth/ResendOTP": typeof lib_auth_ResendOTP;
  "lib/auth/ResendOTPPasswordReset": typeof lib_auth_ResendOTPPasswordReset;
  "lib/auth/getCurrentActor": typeof lib_auth_getCurrentActor;
  "lib/auth/getSession": typeof lib_auth_getSession;
  "lib/auth/index": typeof lib_auth_index;
  "lib/auth/sessions": typeof lib_auth_sessions;
  "lib/cart/cart": typeof lib_cart_cart;
  "lib/cart/index": typeof lib_cart_index;
  "lib/crypto/credentials": typeof lib_crypto_credentials;
  "lib/crypto/envelope": typeof lib_crypto_envelope;
  "lib/crypto/index": typeof lib_crypto_index;
  "lib/customer/address": typeof lib_customer_address;
  "lib/customer/cgv": typeof lib_customer_cgv;
  "lib/customer/checkoutContact": typeof lib_customer_checkoutContact;
  "lib/customer/consent": typeof lib_customer_consent;
  "lib/customer/identity": typeof lib_customer_identity;
  "lib/customer/index": typeof lib_customer_index;
  "lib/customer/kpi": typeof lib_customer_kpi;
  "lib/customer/pushEnrollment": typeof lib_customer_pushEnrollment;
  "lib/customer/reachability": typeof lib_customer_reachability;
  "lib/customer/rgpd": typeof lib_customer_rgpd;
  "lib/customer/segments": typeof lib_customer_segments;
  "lib/customer/webPush": typeof lib_customer_webPush;
  "lib/delivery/course": typeof lib_delivery_course;
  "lib/delivery/incidents": typeof lib_delivery_incidents;
  "lib/delivery/index": typeof lib_delivery_index;
  "lib/delivery/quote": typeof lib_delivery_quote;
  "lib/delivery/webhooks": typeof lib_delivery_webhooks;
  "lib/devices/devices": typeof lib_devices_devices;
  "lib/devices/index": typeof lib_devices_index;
  "lib/menuRevalidate/index": typeof lib_menuRevalidate_index;
  "lib/menuRevalidate/revalidateMenuTag": typeof lib_menuRevalidate_revalidateMenuTag;
  "lib/menu/availability": typeof lib_menu_availability;
  "lib/menu/catalog": typeof lib_menu_catalog;
  "lib/menu/categories": typeof lib_menu_categories;
  "lib/menu/index": typeof lib_menu_index;
  "lib/menu/items": typeof lib_menu_items;
  "lib/menu/modifiers": typeof lib_menu_modifiers;
  "lib/menu/photos": typeof lib_menu_photos;
  "lib/menu/publication": typeof lib_menu_publication;
  "lib/menu/serviceHours": typeof lib_menu_serviceHours;
  "lib/notifications/antiAnomaly": typeof lib_notifications_antiAnomaly;
  "lib/notifications/campaigns": typeof lib_notifications_campaigns;
  "lib/notifications/categories": typeof lib_notifications_categories;
  "lib/notifications/dispatch": typeof lib_notifications_dispatch;
  "lib/notifications/dnt": typeof lib_notifications_dnt;
  "lib/notifications/engine": typeof lib_notifications_engine;
  "lib/notifications/index": typeof lib_notifications_index;
  "lib/notifications/marketingCascade": typeof lib_notifications_marketingCascade;
  "lib/notifications/marketingRateLimit": typeof lib_notifications_marketingRateLimit;
  "lib/notifications/notify": typeof lib_notifications_notify;
  "lib/notifications/reachabilityFeedback": typeof lib_notifications_reachabilityFeedback;
  "lib/notifications/refundIssuedTemplate": typeof lib_notifications_refundIssuedTemplate;
  "lib/notifications/templateBounds": typeof lib_notifications_templateBounds;
  "lib/notifications/unsubscribe": typeof lib_notifications_unsubscribe;
  "lib/onboarding/crm": typeof lib_onboarding_crm;
  "lib/onboarding/csv": typeof lib_onboarding_csv;
  "lib/onboarding/gates": typeof lib_onboarding_gates;
  "lib/onboarding/index": typeof lib_onboarding_index;
  "lib/onboarding/milestones": typeof lib_onboarding_milestones;
  "lib/onboarding/pipeline": typeof lib_onboarding_pipeline;
  "lib/onboarding/provisioning": typeof lib_onboarding_provisioning;
  "lib/onboarding/seedData": typeof lib_onboarding_seedData;
  "lib/orders/index": typeof lib_orders_index;
  "lib/orders/orders": typeof lib_orders_orders;
  "lib/orders/status": typeof lib_orders_status;
  "lib/orders/tracking": typeof lib_orders_tracking;
  "lib/orders/workflow": typeof lib_orders_workflow;
  "lib/pricing/contradictions": typeof lib_pricing_contradictions;
  "lib/pricing/defaultRule": typeof lib_pricing_defaultRule;
  "lib/pricing/evaluate": typeof lib_pricing_evaluate;
  "lib/pricing/index": typeof lib_pricing_index;
  "lib/pricing/rules": typeof lib_pricing_rules;
  "lib/printing/index": typeof lib_printing_index;
  "lib/printing/printing": typeof lib_printing_printing;
  "lib/stats/dailyKpis": typeof lib_stats_dailyKpis;
  "lib/stats/index": typeof lib_stats_index;
  "lib/stats/quickStats": typeof lib_stats_quickStats;
  "lib/stats/rangeAggregates": typeof lib_stats_rangeAggregates;
  "lib/stats/revenuePerDay": typeof lib_stats_revenuePerDay;
  "lib/stripe/account": typeof lib_stripe_account;
  "lib/stripe/dispute": typeof lib_stripe_dispute;
  "lib/stripe/fees": typeof lib_stripe_fees;
  "lib/stripe/index": typeof lib_stripe_index;
  "lib/stripe/payment": typeof lib_stripe_payment;
  "lib/stripe/paymentIntent": typeof lib_stripe_paymentIntent;
  "lib/stripe/refund": typeof lib_stripe_refund;
  "lib/stripe/savedCard": typeof lib_stripe_savedCard;
  "lib/stripe/signature": typeof lib_stripe_signature;
  "lib/stripe/status": typeof lib_stripe_status;
  "lib/stripe/webhook": typeof lib_stripe_webhook;
  "lib/stripe/webhookHandler": typeof lib_stripe_webhookHandler;
  "lib/tenancy/_probes": typeof lib_tenancy__probes;
  "lib/tenancy/adminInvitesStore": typeof lib_tenancy_adminInvitesStore;
  "lib/tenancy/appConfigStore": typeof lib_tenancy_appConfigStore;
  "lib/tenancy/audit": typeof lib_tenancy_audit;
  "lib/tenancy/campaignsStore": typeof lib_tenancy_campaignsStore;
  "lib/tenancy/cgvArchive": typeof lib_tenancy_cgvArchive;
  "lib/tenancy/contractsStore": typeof lib_tenancy_contractsStore;
  "lib/tenancy/customer": typeof lib_tenancy_customer;
  "lib/tenancy/customerFiche": typeof lib_tenancy_customerFiche;
  "lib/tenancy/customerOrdersStore": typeof lib_tenancy_customerOrdersStore;
  "lib/tenancy/deliveriesStore": typeof lib_tenancy_deliveriesStore;
  "lib/tenancy/devicesStore": typeof lib_tenancy_devicesStore;
  "lib/tenancy/fuzz": typeof lib_tenancy_fuzz;
  "lib/tenancy/index": typeof lib_tenancy_index;
  "lib/tenancy/menuStore": typeof lib_tenancy_menuStore;
  "lib/tenancy/notificationsStore": typeof lib_tenancy_notificationsStore;
  "lib/tenancy/ordersStore": typeof lib_tenancy_ordersStore;
  "lib/tenancy/paymentsStore": typeof lib_tenancy_paymentsStore;
  "lib/tenancy/pricingRulesStore": typeof lib_tenancy_pricingRulesStore;
  "lib/tenancy/prospectsStore": typeof lib_tenancy_prospectsStore;
  "lib/tenancy/serviceHoursStore": typeof lib_tenancy_serviceHoursStore;
  "lib/tenancy/stripeAccountStore": typeof lib_tenancy_stripeAccountStore;
  "lib/tenancy/tenantActionGuard": typeof lib_tenancy_tenantActionGuard;
  "lib/tenancy/tenantsStore": typeof lib_tenancy_tenantsStore;
  "lib/tenancy/userTenantsStore": typeof lib_tenancy_userTenantsStore;
  "lib/tenancy/usersStore": typeof lib_tenancy_usersStore;
  "lib/tenancy/walletDeviceRegistrationsStore": typeof lib_tenancy_walletDeviceRegistrationsStore;
  "lib/tenancy/walletIncentiveDeliveriesStore": typeof lib_tenancy_walletIncentiveDeliveriesStore;
  "lib/tenancy/walletPassesStore": typeof lib_tenancy_walletPassesStore;
  "lib/tenancy/webPushSubscriptionsStore": typeof lib_tenancy_webPushSubscriptionsStore;
  "lib/tenancy/withTenant": typeof lib_tenancy_withTenant;
  "lib/tenants/branding": typeof lib_tenants_branding;
  "lib/tenants/index": typeof lib_tenants_index;
  "lib/tenants/payment": typeof lib_tenants_payment;
  "lib/tenants/resolution": typeof lib_tenants_resolution;
  "lib/uberDirect/account": typeof lib_uberDirect_account;
  "lib/uberDirect/createDelivery": typeof lib_uberDirect_createDelivery;
  "lib/uberDirect/credentials": typeof lib_uberDirect_credentials;
  "lib/uberDirect/deliveries": typeof lib_uberDirect_deliveries;
  "lib/uberDirect/index": typeof lib_uberDirect_index;
  "lib/uberDirect/quote": typeof lib_uberDirect_quote;
  "lib/uberDirect/webhookEvents": typeof lib_uberDirect_webhookEvents;
  "lib/wallet/_constants": typeof lib_wallet__constants;
  "lib/wallet/bridgeSerialToSession": typeof lib_wallet_bridgeSerialToSession;
  "lib/wallet/checkInstallStatus": typeof lib_wallet_checkInstallStatus;
  "lib/wallet/generatePass": typeof lib_wallet_generatePass;
  "lib/wallet/incentive": typeof lib_wallet_incentive;
  "lib/wallet/index": typeof lib_wallet_index;
  "lib/wallet/internalAuth": typeof lib_wallet_internalAuth;
  "lib/wallet/linkSerial": typeof lib_wallet_linkSerial;
  "lib/wallet/passBuilders": typeof lib_wallet_passBuilders;
  "lib/wallet/passDb": typeof lib_wallet_passDb;
  "lib/wallet/pushPayload": typeof lib_wallet_pushPayload;
  "lib/wallet/registrations": typeof lib_wallet_registrations;
  "lib/wallet/triggerUpdate": typeof lib_wallet_triggerUpdate;
  "lib/wallet/webService": typeof lib_wallet_webService;
  "lib/webhooks/idempotent": typeof lib_webhooks_idempotent;
  "lib/webhooks/index": typeof lib_webhooks_index;
  migrations: typeof migrations;
  storage: typeof storage;
  "table/admin": typeof table_admin;
  "table/adminInvites": typeof table_adminInvites;
  "table/appConfig": typeof table_appConfig;
  "table/auditLog": typeof table_auditLog;
  "table/cgvVersions": typeof table_cgvVersions;
  "table/contracts": typeof table_contracts;
  "table/customerOrdersPerTenant": typeof table_customerOrdersPerTenant;
  "table/customers": typeof table_customers;
  "table/deliveries": typeof table_deliveries;
  "table/devices": typeof table_devices;
  "table/feedback": typeof table_feedback;
  "table/menuCategories": typeof table_menuCategories;
  "table/menuItemModifierGroups": typeof table_menuItemModifierGroups;
  "table/menuItems": typeof table_menuItems;
  "table/modifierGroups": typeof table_modifierGroups;
  "table/notifications": typeof table_notifications;
  "table/orders": typeof table_orders;
  "table/payments": typeof table_payments;
  "table/pricingRules": typeof table_pricingRules;
  "table/processedWebhookEvents": typeof table_processedWebhookEvents;
  "table/prospects": typeof table_prospects;
  "table/publishedMenus": typeof table_publishedMenus;
  "table/serviceHours": typeof table_serviceHours;
  "table/tenantCredentials": typeof table_tenantCredentials;
  "table/tenants": typeof table_tenants;
  "table/userTenants": typeof table_userTenants;
  "table/users": typeof table_users;
  "table/walletDeviceRegistrations": typeof table_walletDeviceRegistrations;
  "table/walletIncentiveDeliveries": typeof table_walletIncentiveDeliveries;
  "table/walletPasses": typeof table_walletPasses;
  "table/webPushSubscriptions": typeof table_webPushSubscriptions;
  "utils/generateFunctions": typeof utils_generateFunctions;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
};
